#!/bin/bash
set -e

## this is a very generic way of installing a specific python version + deps
## general idea from: http://stackoverflow.com/a/11301911/1705163
## the system installing this need a compiler and libs to build python

usage() {
  SCRIPT_NAME=$(basename "${BASH_SOURCE[0]}")
  echo "Usage: $SCRIPT_NAME -d <dir> -p <python version> -v <virtualenv version> -f"
  echo "  f to force download even if <dir> already exists"
  echo "Example: $SCRIPT_NAME -d ve -p 2.7.7 -v 1.11.6 -f"
  exit 1
}

while getopts ":d:p:v:fh" opt; do
  case $opt in
    h) usage ;;
    d) DIR=$OPTARG ;;
    p) PYVERSION=$OPTARG ;;
    v) VEVERSION=$OPTARG ;;
    f) FORCE=1 ;;
    :) echo "Option -$OPTARG requires an argument." >&2 ;;
    \?) echo "Invalid option: -$OPTARG" >&2 ;;
  esac
done

if [[ -z "$DIR" || -z "$PYVERSION" || -z "$VEVERSION" ]]; then
  usage
fi

if [[ "$OSTYPE" == "darwin"* ]]; then
  DEST=$(greadlink -f $DIR)
else
  DEST=$(readlink -f $DIR)
fi

VEDIR=$DEST/virtualenv/ve

#setup python
install_python() {
    pushd . > /dev/null
    local SRCDIR=$DEST/python/src
    local INSTALLDIR=$DEST/python/install
    mkdir -p $SRCDIR $INSTALLDIR
    if [[ -d $SRCDIR  && -d $INSTALLDIR ]]; then
        cd $SRCDIR
        local TARBALL=Python-$PYVERSION.tgz
        echo "downloading $TARBALL..."
        curl --silent -O https://www.python.org/ftp/python/$PYVERSION/$TARBALL
        tar -zxvf $TARBALL > /dev/null
        cd Python-$PYVERSION
        ./configure --prefix=$INSTALLDIR > /dev/null
        echo "building Python-$PYVERSION..."
        make > /dev/null 2>&1 #also eat stderr; there are always warnings
        make install > /dev/null
        PYTHON=$INSTALLDIR/bin/python
        if [ ! -e "$PYTHON" ]; then
            PYTHON=$INSTALLDIR/bin/python3
        fi
    else
        echo "unable to create $SRCDIR and/or $INSTALLDIR" >&2
        exit 1
    fi
    popd
}

#setup virtualenv
install_virtualenv() {
    pushd . > /dev/null
    local SRCDIR=$DEST/virtualenv/src
    mkdir -p $SRCDIR $VEDIR
    if [[ -d $SRCDIR  && -d $VEDIR ]]; then
        cd $SRCDIR
        local TARBALL=virtualenv-$VEVERSION.tar.gz
        curl --silent -O https://pypi.python.org/packages/source/v/virtualenv/$TARBALL
        tar -zxvf $TARBALL > /dev/null
        cd virtualenv-$VEVERSION
        if [ -z "$PYTHON" ]; then
            echo "no python: $PYTHON" >&2
            exit 1
        else
            $PYTHON virtualenv.py $VEDIR -p $PYTHON --no-site-packages
        fi
    else
        echo "unable to create $SRCDIR and/or $VEDIR" >&2
        exit 1
    fi
    popd
}

echo "absolute destination path: $DEST"
if [[ $FORCE && -d $DEST ]]; then
    echo "forcing install: removing $DEST"
    rm -rf $DEST
fi

if [ -d $DEST ]; then
    echo "skipping install: $DEST exists"
else
    #run the installation
    echo "Installing Python $PYVERSION..."
        install_python
    if [ -e $INSTALLDIR/bin/pyvenv ]; then
        echo "Creating Virtual Env using Python provided pyvenv"
        $INSTALLDIR/bin/pyvenv $VEDIR
    else
        echo "Installing Virtualenv $VEVERSION..."
        install_virtualenv
    fi
    #create a more convenient / findable activate link
    ACTIVATE=$DEST/activate
    ln -sf $VEDIR/bin/activate $ACTIVATE
fi

echo done
exit 0
